### ISSUE TITLE
Meeting 19. 11. 2018

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/flashcards#145]
Implement web w/o play and search.

showcase:

* [x] how web (AngularDart) works – components, routes, ...

web:

* [x] update to newest AngularDart (https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md)
* [ ] add web course's sections #153
* [ ] add translations support #125
* [x] add about page #154
* [ ] add licences page (automatically generated) #155

need auth:

* [x] add web sign in #83
* [x] add web user profile #152

---

mobile:

* [ ] Enhance mobile search #132 
* [ ] Add cards to course's section #140 
* [ ] Fix mobile sign in false positives #156 
* [ ] Fix user profile edit #157 

---

* [x] Close #144

**Comment by tenhobi** [comment]
To be able to use `FlashcardsStrings` in templates, use 

```
  exports: [
    FlashcardsStrings,
  ],
```
